### PR TITLE
Adds the ability to pass in different case of unit such as "500 kb", "4 mb", etc.

### PR DESCRIPTION
**Pull request by drewry**
Modifies the switch to downcase all units so that "500 kb" does not return nil

### CODE REVIEW

**Comment by zedtux** [comment]
Thanks @drewry for this PR :+1: 
- Please let the repository owner managing the version
- Can you check why the build is not passing ?

**Comment by drewry** [comment]
> Please let the repository owner managing the version

Yea sorry about that, I am using it on a project and was getting a version conflict issue so tried changing it on my fork to resolve it.  I'll change it back and just go off of the commit hash.

> Can you check why the build is not passing ?

So it looks like an rcov issue:

```
NoMethodError: undefined method `rcov=' for #<RSpec::Core::RakeTask:0x7fb1c78a3a88>
```

It's failing on 1.8.7 and ree.  All of the research I have done on it says that the solution is to do `require 'rspec/core'` but we are already doing that so I'm a little confused why it's not working.  Do you have any ideas?

**Comment by zedtux** [comment]
>  Do you have any ideas?

... maybe a newer version of Rspec ...

**Comment by drewry** [comment]
@zedtux ready for merge if all looks good, that build sure took a while :smile:

**Comment by zedtux** [comment]
@drewry it's merged, thank you 👍

**Pull request merged**
